input_bag: /media/dbutterfield3/T71/Hercules_datasets/V1.2/ausenv_test1_checkpoints_CSLAM_2UAVUGV
external_msgs_path_ros2: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros2
external_msgs_path_ros1: /home/dbutterfield3/Research/rosbag_manip/external_msgs_ros1
operation_to_run: extract_odometry_to_csv
operation_params:
  extract_odometry_to_csv:
    topic: /hercules_node/Drone1/ground_truth/odom_local
    output_file: /media/dbutterfield3/T71/Hercules_datasets/V1.2/extract/Drone1_odomGT.csv
    add_noise: False
    xy_noise_std_per_frame: 0.0001
    z_noise_std_per_frame: 0.00001
    shift_position_xy: 50
    shift_position_z: 10